name: Hello World
on: workflow_dispatch
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: echo A demo build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test phase
        run: echo Running

  deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Deploy the app
       run: echo deploying the app
     
