name: variable d environnement
on: [push, workflow_dispatch]

jobs:
  build_api:
   runs-on: windows-latest
   env:
      FilesNumber: dirre
   steps:
    - name: recuperer files
      run: echo "lire les $FilesNumber fichiers"
